services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bpsdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    container_name: budgetplanner-backend
    build:
      context: ./budgetplannerbackend
      dockerfile: ../BUDGET_PLANNER_FULLSTACK/backend.Dockerfile
    ports:
      - "2099:2099"
    depends_on:
      - mysqldb
    restart: on-failure

  frontend:
    container_name: budgetplanner-frontend
    build:
      context: ./budgetplannerfrontend
      dockerfile: ../BUDGET_PLANNER_FULLSTACK/frontend.Dockerfile
    ports:
      - "2098:80"
    depends_on:
      - backend

volumes:
  mysql-data:
